# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 679)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.runButton = QtWidgets.QPushButton(self.centralWidget)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout.addWidget(self.runButton)
        self.checkLimitation = QtWidgets.QCheckBox(self.centralWidget)
        self.checkLimitation.setChecked(True)
        self.checkLimitation.setObjectName("checkLimitation")
        self.horizontalLayout.addWidget(self.checkLimitation)
        self.limitationLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.limitationLineEdit.setObjectName("limitationLineEdit")
        self.horizontalLayout.addWidget(self.limitationLineEdit)
        self.stepButton = QtWidgets.QPushButton(self.centralWidget)
        self.stepButton.setObjectName("stepButton")
        self.horizontalLayout.addWidget(self.stepButton)
        self.resetButton = QtWidgets.QPushButton(self.centralWidget)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.increaseSize = QtWidgets.QPushButton(self.centralWidget)
        self.increaseSize.setObjectName("increaseSize")
        self.horizontalLayout.addWidget(self.increaseSize)
        self.decreaseSize = QtWidgets.QPushButton(self.centralWidget)
        self.decreaseSize.setObjectName("decreaseSize")
        self.horizontalLayout.addWidget(self.decreaseSize)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.codeBox = QtWidgets.QGroupBox(self.centralWidget)
        self.codeBox.setObjectName("codeBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.codeBox)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.codeTextEdit = QtWidgets.QTextEdit(self.codeBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.codeTextEdit.setFont(font)
        self.codeTextEdit.setObjectName("codeTextEdit")
        self.horizontalLayout_2.addWidget(self.codeTextEdit)
        self.verticalLayout_3.addWidget(self.codeBox)
        self.resultBox = QtWidgets.QGroupBox(self.centralWidget)
        self.resultBox.setObjectName("resultBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.resultBox)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.resultTextEdit = QtWidgets.QTextEdit(self.resultBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.resultTextEdit.setFont(font)
        self.resultTextEdit.setReadOnly(True)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.verticalLayout.addWidget(self.resultTextEdit)
        self.verticalLayout_3.addWidget(self.resultBox)
        self.intermedBox = QtWidgets.QGroupBox(self.centralWidget)
        self.intermedBox.setObjectName("intermedBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.intermedBox)
        self.verticalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.intermediateTextEdit = QtWidgets.QTextEdit(self.intermedBox)
        font = QtGui.QFont()
        font.setFamily("Courier New")
        self.intermediateTextEdit.setFont(font)
        self.intermediateTextEdit.setReadOnly(True)
        self.intermediateTextEdit.setObjectName("intermediateTextEdit")
        self.verticalLayout_2.addWidget(self.intermediateTextEdit)
        self.verticalLayout_3.addWidget(self.intermedBox)
        MainWindow.setCentralWidget(self.centralWidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.checkLimitation.toggled['bool'].connect(self.limitationLineEdit.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "/// Interpreter"))
        self.runButton.setText(_translate("MainWindow", "Run (Ctrl-R)"))
        self.checkLimitation.setText(_translate("MainWindow", "Limit substitutions to:"))
        self.limitationLineEdit.setText(_translate("MainWindow", "1000"))
        self.stepButton.setText(_translate("MainWindow", "Step (Ctrl-S)"))
        self.resetButton.setText(_translate("MainWindow", "Reset Steps (Ctrl-C)"))
        self.increaseSize.setText(_translate("MainWindow", "+"))
        self.decreaseSize.setText(_translate("MainWindow", "-"))
        self.codeBox.setTitle(_translate("MainWindow", "Code"))
        self.resultBox.setTitle(_translate("MainWindow", "Result"))
        self.intermedBox.setTitle(_translate("MainWindow", "Intermediate code:"))

